"""edited users table

Revision ID: 13c21c4be5f4
Revises: 909154b58252
Create Date: 2026-02-05 09:41:40.061262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13c21c4be5f4'
down_revision: Union[str, Sequence[str], None] = '909154b58252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nationality', sa.VARCHAR(length=25), nullable=False))
    op.drop_column('users', 'is_suspended')
    op.drop_column('users', 'suspended_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('suspended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_suspended', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'nationality')
    # ### end Alembic commands ###
