"""created instructor relationship in Course model and changed column name to instructor_id

Revision ID: 6127d64c9f30
Revises: 13c21c4be5f4
Create Date: 2026-02-07 16:59:22.798173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6127d64c9f30'
down_revision: Union[str, Sequence[str], None] = '13c21c4be5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('instructor_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('courses_instructor_fk'), 'courses', type_='foreignkey')
    op.create_foreign_key('courses_instructor_fk', 'courses', 'users', ['instructor_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('courses', 'instructor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('instructor', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('courses_instructor_fk', 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_instructor_fk'), 'courses', 'users', ['instructor'], ['id'], ondelete='RESTRICT')
    op.drop_column('courses', 'instructor_id')
    # ### end Alembic commands ###
