"""configured model relationship and on delete actions

Revision ID: 909154b58252
Revises: fb43b386cb97
Create Date: 2026-02-03 14:09:36.478433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909154b58252'
down_revision: Union[str, Sequence[str], None] = 'fb43b386cb97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('courses_instructor_fk'), 'courses', type_='foreignkey')
    op.create_foreign_key('courses_instructor_fk', 'courses', 'users', ['instructor'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('enrol_user_id_fk'), 'enrollments', type_='foreignkey')
    op.drop_constraint(op.f('enrol_course_id_fk'), 'enrollments', type_='foreignkey')
    op.create_foreign_key('enrol_course_id_fk', 'enrollments', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('enrol_user_id_fk', 'enrollments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_role_id_fk'), 'users', type_='foreignkey')
    op.create_foreign_key('users_role_id_fk', 'users', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_role_id_fk', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fk'), 'users', 'roles', ['role_id'], ['id'])
    op.drop_constraint('enrol_user_id_fk', 'enrollments', type_='foreignkey')
    op.drop_constraint('enrol_course_id_fk', 'enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('enrol_course_id_fk'), 'enrollments', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(op.f('enrol_user_id_fk'), 'enrollments', 'users', ['user_id'], ['id'])
    op.drop_constraint('courses_instructor_fk', 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_instructor_fk'), 'courses', 'users', ['instructor'], ['id'])
    # ### end Alembic commands ###
