"""introduced a check constraint on courses.capacity and fixed secondary table passed to users.courses and courses.users

Revision ID: 937eae0c47d8
Revises: 6127d64c9f30
Create Date: 2026-02-07 17:46:01.357150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937eae0c47d8'
down_revision: Union[str, Sequence[str], None] = '6127d64c9f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
