"""database table generation

Revision ID: fb43b386cb97
Revises: 33b9f5595ca5
Create Date: 2026-02-03 03:39:07.403383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb43b386cb97'
down_revision: Union[str, Sequence[str], None] = '33b9f5595ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('ADMIN', 'USER', 'INSTRUCTOR', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='roles_id_pk'),
    sa.UniqueConstraint('name', name='roles_name_unique_key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=20), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='users_role_id_fk'),
    sa.PrimaryKeyConstraint('id', name='users_id_pk'),
    sa.UniqueConstraint('email', name='users_email_unique_key')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_name', 'users', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('idx_users_role_id', 'users', ['role_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), nullable=False),
    sa.Column('description', sa.VARCHAR(length=50), nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('instructor', sa.UUID(), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instructor'], ['users.id'], name='courses_instructor_fk'),
    sa.PrimaryKeyConstraint('id', name='courses_id_pk'),
    sa.UniqueConstraint('code', name='courses_code_unique_key')
    )
    op.create_index('idx_courses_title', 'courses', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'REVOKED', 'USED', name='tokenstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tokens_user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='refresh_tokens_pk')
    )
    op.create_index('idx_auth_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='enrol_course_id_fk'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='enrol_user_id_fk'),
    sa.PrimaryKeyConstraint('user_id', 'course_id', name='enrol_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    op.drop_index('idx_auth_user_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_courses_title', table_name='courses', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_table('courses')
    op.drop_index('idx_users_role_id', table_name='users')
    op.drop_index('idx_users_name', table_name='users', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
